/*
  Warnings:

  - You are about to drop the `Widget` table. If the table is not empty, all the data it contains will be lost.
  - A unique constraint covering the columns `[kaprodiId]` on the table `prodi` will be added. If there are existing duplicate values, this will fail.
  - Added the required column `KKId` to the `MK` table without a default value. This is not possible if the table is not empty.
  - Added the required column `rumpun` to the `MK` table without a default value. This is not possible if the table is not empty.
  - Added the required column `kaprodiId` to the `prodi` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE "MK" ADD COLUMN     "KKId" INT4 NOT NULL;
ALTER TABLE "MK" ADD COLUMN     "rumpun" STRING NOT NULL;

-- AlterTable
ALTER TABLE "prodi" ADD COLUMN     "kaprodiId" INT4 NOT NULL;

-- DropTable
DROP TABLE "Widget";

-- CreateTable
CREATE TABLE "kelompokKeahlian" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nama" STRING NOT NULL,
    "ketuaId" INT4 NOT NULL,
    "prodiId" STRING NOT NULL,

    CONSTRAINT "kelompokKeahlian_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rps" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "MKId" STRING NOT NULL,
    "pengembangId" INT4 NOT NULL,
    "deskripsi" STRING NOT NULL,
    "pustakaUtama" STRING NOT NULL,
    "pustakaPendukung" STRING NOT NULL,
    "software" STRING NOT NULL,
    "hardware" STRING NOT NULL,
    "revisi" STRING NOT NULL,

    CONSTRAINT "rps_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_Prerequisites" (
    "A" STRING NOT NULL,
    "B" STRING NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "kelompokKeahlian_id_key" ON "kelompokKeahlian"("id");

-- CreateIndex
CREATE UNIQUE INDEX "kelompokKeahlian_ketuaId_key" ON "kelompokKeahlian"("ketuaId");

-- CreateIndex
CREATE UNIQUE INDEX "rps_id_key" ON "rps"("id");

-- CreateIndex
CREATE UNIQUE INDEX "rps_MKId_key" ON "rps"("MKId");

-- CreateIndex
CREATE UNIQUE INDEX "_Prerequisites_AB_unique" ON "_Prerequisites"("A", "B");

-- CreateIndex
CREATE INDEX "_Prerequisites_B_index" ON "_Prerequisites"("B");

-- CreateIndex
CREATE UNIQUE INDEX "prodi_kaprodiId_key" ON "prodi"("kaprodiId");

-- AddForeignKey
ALTER TABLE "prodi" ADD CONSTRAINT "prodi_kaprodiId_fkey" FOREIGN KEY ("kaprodiId") REFERENCES "account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kelompokKeahlian" ADD CONSTRAINT "kelompokKeahlian_ketuaId_fkey" FOREIGN KEY ("ketuaId") REFERENCES "account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kelompokKeahlian" ADD CONSTRAINT "kelompokKeahlian_prodiId_fkey" FOREIGN KEY ("prodiId") REFERENCES "prodi"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MK" ADD CONSTRAINT "MK_KKId_fkey" FOREIGN KEY ("KKId") REFERENCES "kelompokKeahlian"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rps" ADD CONSTRAINT "rps_MKId_fkey" FOREIGN KEY ("MKId") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rps" ADD CONSTRAINT "rps_pengembangId_fkey" FOREIGN KEY ("pengembangId") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_Prerequisites" ADD CONSTRAINT "_Prerequisites_A_fkey" FOREIGN KEY ("A") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_Prerequisites" ADD CONSTRAINT "_Prerequisites_B_fkey" FOREIGN KEY ("B") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;
