/*
  Warnings:

  - You are about to drop the column `rencanaPembelajaran` on the `MK` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "MK" DROP COLUMN "rencanaPembelajaran";

-- CreateTable
CREATE TABLE "rencanaPembelajaran" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "minggu" STRING NOT NULL,
    "materi" STRING NOT NULL,
    "metode" STRING NOT NULL,
    "MKId" STRING NOT NULL,

    CONSTRAINT "rencanaPembelajaran_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "rencanaPembelajaran_id_key" ON "rencanaPembelajaran"("id");

-- AddForeignKey
ALTER TABLE "rencanaPembelajaran" ADD CONSTRAINT "rencanaPembelajaran_MKId_fkey" FOREIGN KEY ("MKId") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;
