/*
  Warnings:

  - Added the required column `templatePenilaianCPMKId` to the `penilaianCPMK` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE "penilaianCPMK" ADD COLUMN     "templatePenilaianCPMKId" INT4 NOT NULL;

-- CreateTable
CREATE TABLE "templatePenilaianCPMK" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "template" STRING NOT NULL,
    "MKId" STRING NOT NULL,

    CONSTRAINT "templatePenilaianCPMK_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "templatePenilaianCPMK_id_key" ON "templatePenilaianCPMK"("id");

-- CreateIndex
CREATE INDEX "templatePenilaianCPMK_MKId_idx" ON "templatePenilaianCPMK"("MKId");

-- AddForeignKey
ALTER TABLE "templatePenilaianCPMK" ADD CONSTRAINT "templatePenilaianCPMK_MKId_fkey" FOREIGN KEY ("MKId") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "penilaianCPMK" ADD CONSTRAINT "penilaianCPMK_templatePenilaianCPMKId_fkey" FOREIGN KEY ("templatePenilaianCPMKId") REFERENCES "templatePenilaianCPMK"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
