-- AlterSequence
ALTER SEQUENCE "_prisma_new_penilaianCPMK_id_seq" MAXVALUE 9223372036854775807;

-- CreateTable
CREATE TABLE "mahasiswa" (
    "nim" STRING NOT NULL,
    "nama" STRING NOT NULL,

    CONSTRAINT "mahasiswa_pkey" PRIMARY KEY ("nim")
);

-- CreateTable
CREATE TABLE "inputNilai" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "penilaianCPMKId" INT4 NOT NULL,
    "mahasiswaNim" STRING NOT NULL,
    "nilai" FLOAT8[]
);

-- CreateTable
CREATE TABLE "_mk_mahasiswa" (
    "A" STRING NOT NULL,
    "B" STRING NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "mahasiswa_nim_key" ON "mahasiswa"("nim");

-- CreateIndex
CREATE UNIQUE INDEX "inputNilai_id_key" ON "inputNilai"("id");

-- CreateIndex
CREATE UNIQUE INDEX "_mk_mahasiswa_AB_unique" ON "_mk_mahasiswa"("A", "B");

-- CreateIndex
CREATE INDEX "_mk_mahasiswa_B_index" ON "_mk_mahasiswa"("B");

-- AddForeignKey
ALTER TABLE "inputNilai" ADD CONSTRAINT "inputNilai_penilaianCPMKId_fkey" FOREIGN KEY ("penilaianCPMKId") REFERENCES "penilaianCPMK"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inputNilai" ADD CONSTRAINT "inputNilai_mahasiswaNim_fkey" FOREIGN KEY ("mahasiswaNim") REFERENCES "mahasiswa"("nim") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_mk_mahasiswa" ADD CONSTRAINT "_mk_mahasiswa_A_fkey" FOREIGN KEY ("A") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_mk_mahasiswa" ADD CONSTRAINT "_mk_mahasiswa_B_fkey" FOREIGN KEY ("B") REFERENCES "mahasiswa"("nim") ON DELETE CASCADE ON UPDATE CASCADE;
