/*
  Warnings:

  - You are about to drop the column `materi` on the `rencanaPembelajaran` table. All the data in the column will be lost.
  - Added the required column `bahanKajian` to the `rencanaPembelajaran` table without a default value. This is not possible if the table is not empty.
  - Added the required column `bentuk` to the `rencanaPembelajaran` table without a default value. This is not possible if the table is not empty.
  - Added the required column `pengalaman` to the `rencanaPembelajaran` table without a default value. This is not possible if the table is not empty.
  - Added the required column `penilaianCPMKId` to the `rencanaPembelajaran` table without a default value. This is not possible if the table is not empty.
  - Added the required column `sumber` to the `rencanaPembelajaran` table without a default value. This is not possible if the table is not empty.
  - Added the required column `waktu` to the `rencanaPembelajaran` table without a default value. This is not possible if the table is not empty.
  - Added the required column `signatureGKMP` to the `rps` table without a default value. This is not possible if the table is not empty.
  - Added the required column `signatureKaprodi` to the `rps` table without a default value. This is not possible if the table is not empty.
  - Added the required column `signatureKetuaKK` to the `rps` table without a default value. This is not possible if the table is not empty.
  - Added the required column `signaturePengembang` to the `rps` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE "rencanaPembelajaran" DROP COLUMN "materi";
ALTER TABLE "rencanaPembelajaran" ADD COLUMN     "bahanKajian" STRING NOT NULL;
ALTER TABLE "rencanaPembelajaran" ADD COLUMN     "bentuk" STRING NOT NULL;
ALTER TABLE "rencanaPembelajaran" ADD COLUMN     "pengalaman" STRING NOT NULL;
ALTER TABLE "rencanaPembelajaran" ADD COLUMN     "penilaianCPMKId" INT4 NOT NULL;
ALTER TABLE "rencanaPembelajaran" ADD COLUMN     "sumber" STRING NOT NULL;
ALTER TABLE "rencanaPembelajaran" ADD COLUMN     "waktu" STRING NOT NULL;

-- AlterTable
ALTER TABLE "rps" ADD COLUMN     "signatureGKMP" STRING NOT NULL;
ALTER TABLE "rps" ADD COLUMN     "signatureKaprodi" STRING NOT NULL;
ALTER TABLE "rps" ADD COLUMN     "signatureKetuaKK" STRING NOT NULL;
ALTER TABLE "rps" ADD COLUMN     "signaturePengembang" STRING NOT NULL;

-- CreateTable
CREATE TABLE "penilaianRP" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kriteria" STRING NOT NULL,
    "indikator" STRING NOT NULL,
    "bobot" FLOAT8 NOT NULL,
    "rencanaPembelajaranId" INT4 NOT NULL,

    CONSTRAINT "penilaianRP_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "penilaianRP_id_key" ON "penilaianRP"("id");

-- CreateIndex
CREATE INDEX "penilaianRP_rencanaPembelajaranId_idx" ON "penilaianRP"("rencanaPembelajaranId");

-- CreateIndex
CREATE INDEX "rencanaPembelajaran_penilaianCPMKId_idx" ON "rencanaPembelajaran"("penilaianCPMKId");

-- AddForeignKey
ALTER TABLE "rencanaPembelajaran" ADD CONSTRAINT "rencanaPembelajaran_penilaianCPMKId_fkey" FOREIGN KEY ("penilaianCPMKId") REFERENCES "penilaianCPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "penilaianRP" ADD CONSTRAINT "penilaianRP_rencanaPembelajaranId_fkey" FOREIGN KEY ("rencanaPembelajaranId") REFERENCES "rencanaPembelajaran"("id") ON DELETE CASCADE ON UPDATE CASCADE;
