/*
  Warnings:

  - You are about to drop the column `testing` on the `MK` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "MK" DROP COLUMN "testing";

-- CreateTable
CREATE TABLE "inputNilai" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "penilaianCPMKId" STRING NOT NULL,
    "mahasiswaNim" STRING NOT NULL,
    "nilai" FLOAT8[]
);

-- CreateIndex
CREATE UNIQUE INDEX "inputNilai_id_key" ON "inputNilai"("id");

-- AddForeignKey
ALTER TABLE "inputNilai" ADD CONSTRAINT "inputNilai_penilaianCPMKId_fkey" FOREIGN KEY ("penilaianCPMKId") REFERENCES "penilaianCPMK"("kode") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inputNilai" ADD CONSTRAINT "inputNilai_mahasiswaNim_fkey" FOREIGN KEY ("mahasiswaNim") REFERENCES "mahasiswa"("nim") ON DELETE RESTRICT ON UPDATE CASCADE;
