-- AlterSequence
ALTER SEQUENCE "lulusCPMK_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "mahasiswa_CPMK_id_seq" MAXVALUE 9223372036854775807;

-- AlterTable
ALTER TABLE "kelas" ADD COLUMN     "tindakLanjutCPL" STRING;
ALTER TABLE "kelas" ADD COLUMN     "tindakLanjutCPMK" STRING;

-- CreateTable
CREATE TABLE "evaluasiCPMKKelas" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kelasId" INT4 NOT NULL,
    "CPMKId" INT4 NOT NULL,
    "evaluasi" STRING NOT NULL,

    CONSTRAINT "evaluasiCPMKKelas_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "evaluasiCPLKelas" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kelasId" INT4 NOT NULL,
    "CPLId" INT4 NOT NULL,
    "evaluasi" STRING NOT NULL,

    CONSTRAINT "evaluasiCPLKelas_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "evaluasiCPMKKelas_id_key" ON "evaluasiCPMKKelas"("id");

-- CreateIndex
CREATE INDEX "evaluasiCPMKKelas_kelasId_idx" ON "evaluasiCPMKKelas"("kelasId");

-- CreateIndex
CREATE INDEX "evaluasiCPMKKelas_CPMKId_idx" ON "evaluasiCPMKKelas"("CPMKId");

-- CreateIndex
CREATE UNIQUE INDEX "evaluasiCPMKKelas_kelasId_CPMKId_key" ON "evaluasiCPMKKelas"("kelasId", "CPMKId");

-- CreateIndex
CREATE UNIQUE INDEX "evaluasiCPLKelas_id_key" ON "evaluasiCPLKelas"("id");

-- CreateIndex
CREATE INDEX "evaluasiCPLKelas_kelasId_idx" ON "evaluasiCPLKelas"("kelasId");

-- CreateIndex
CREATE INDEX "evaluasiCPLKelas_CPLId_idx" ON "evaluasiCPLKelas"("CPLId");

-- CreateIndex
CREATE UNIQUE INDEX "evaluasiCPLKelas_kelasId_CPLId_key" ON "evaluasiCPLKelas"("kelasId", "CPLId");

-- AddForeignKey
ALTER TABLE "evaluasiCPMKKelas" ADD CONSTRAINT "evaluasiCPMKKelas_kelasId_fkey" FOREIGN KEY ("kelasId") REFERENCES "kelas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evaluasiCPMKKelas" ADD CONSTRAINT "evaluasiCPMKKelas_CPMKId_fkey" FOREIGN KEY ("CPMKId") REFERENCES "CPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evaluasiCPLKelas" ADD CONSTRAINT "evaluasiCPLKelas_kelasId_fkey" FOREIGN KEY ("kelasId") REFERENCES "kelas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evaluasiCPLKelas" ADD CONSTRAINT "evaluasiCPLKelas_CPLId_fkey" FOREIGN KEY ("CPLId") REFERENCES "CPL"("id") ON DELETE CASCADE ON UPDATE CASCADE;
