-- CreateTable
CREATE TABLE "kunci" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kunci" BOOL NOT NULL,

    CONSTRAINT "kunci_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "kunci_id_key" ON "kunci"("id");
