/*
  Warnings:

  - The primary key for the `penilaianCPMK` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to drop the column `kode` on the `penilaianCPMK` table. All the data in the column will be lost.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_penilaianCPMK" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CPL" STRING NOT NULL,
    "MK" STRING NOT NULL,
    "CPMK" STRING NOT NULL,
    "tahapPenilaian" STRING NOT NULL,
    "teknikPenilaian" STRING NOT NULL,
    "instrumen" STRING NOT NULL,
    "kriteria" JSONB NOT NULL
);
DROP INDEX "penilaianCPMK_kode_key";
INSERT INTO "_prisma_new_penilaianCPMK" ("CPL","CPMK","MK","instrumen","kriteria","tahapPenilaian","teknikPenilaian") SELECT "CPL","CPMK","MK","instrumen","kriteria","tahapPenilaian","teknikPenilaian" FROM "penilaianCPMK";
DROP TABLE "penilaianCPMK" CASCADE;
ALTER TABLE "_prisma_new_penilaianCPMK" RENAME TO "penilaianCPMK";
CREATE UNIQUE INDEX "penilaianCPMK_id_key" ON "penilaianCPMK"("id");
