-- AlterSequence
ALTER SEQUENCE "CPL_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "kelas_id_seq" MAXVALUE 9223372036854775807;

-- CreateTable
CREATE TABLE "kelas_mahasiswa" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "mahasiswaNim" STRING NOT NULL,
    "kelasId" INT4 NOT NULL,
    "MKId" STRING NOT NULL,

    CONSTRAINT "kelas_mahasiswa_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "kelas_mahasiswa_id_key" ON "kelas_mahasiswa"("id");

-- CreateIndex
CREATE UNIQUE INDEX "kelas_mahasiswa_mahasiswaNim_MKId_key" ON "kelas_mahasiswa"("mahasiswaNim", "MKId");

-- AddForeignKey
ALTER TABLE "kelas_mahasiswa" ADD CONSTRAINT "kelas_mahasiswa_mahasiswaNim_fkey" FOREIGN KEY ("mahasiswaNim") REFERENCES "mahasiswa"("nim") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kelas_mahasiswa" ADD CONSTRAINT "kelas_mahasiswa_kelasId_fkey" FOREIGN KEY ("kelasId") REFERENCES "kelas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kelas_mahasiswa" ADD CONSTRAINT "kelas_mahasiswa_MKId_fkey" FOREIGN KEY ("MKId") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;
