-- CreateTable
CREATE TABLE "Widget" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),

    CONSTRAINT "Widget_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "prodi" (
    "kode" STRING NOT NULL,
    "nama" STRING NOT NULL,

    CONSTRAINT "prodi_pkey" PRIMARY KEY ("kode")
);

-- CreateTable
CREATE TABLE "account" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nama" STRING NOT NULL,
    "email" STRING NOT NULL,
    "role" STRING NOT NULL,
    "password" STRING NOT NULL,
    "prodiId" STRING NOT NULL,

    CONSTRAINT "account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PL" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kode" STRING NOT NULL,
    "deskripsi" STRING NOT NULL,
    "prodiId" STRING,

    CONSTRAINT "PL_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CPL" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kode" STRING NOT NULL,
    "deskripsi" STRING NOT NULL,
    "keterangan" STRING NOT NULL,
    "prodiId" STRING NOT NULL,

    CONSTRAINT "CPL_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BK" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kode" STRING NOT NULL,
    "deskripsi" STRING NOT NULL,
    "min" INT4 NOT NULL,
    "max" INT4 NOT NULL,
    "prodiId" STRING NOT NULL,

    CONSTRAINT "BK_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MK" (
    "kode" STRING NOT NULL,
    "deskripsi" STRING NOT NULL,
    "sks" STRING NOT NULL,
    "batasLulusMahasiswa" FLOAT8 NOT NULL,
    "batasLulusMK" FLOAT8 NOT NULL,
    "jumlahLulus" INT4 NOT NULL,
    "prodiId" STRING NOT NULL,

    CONSTRAINT "MK_pkey" PRIMARY KEY ("kode")
);

-- CreateTable
CREATE TABLE "rencanaPembelajaran" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "minggu" INT4 NOT NULL,
    "materi" STRING NOT NULL,
    "metode" STRING NOT NULL,
    "MKId" STRING NOT NULL,

    CONSTRAINT "rencanaPembelajaran_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kelas" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nama" STRING NOT NULL,
    "MKId" STRING NOT NULL,
    "jumlahLulus" INT4 NOT NULL,
    "mahasiswaLulus" JSONB,
    "dataCPMK" JSONB,

    CONSTRAINT "kelas_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CPMK" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kode" STRING NOT NULL,
    "deskripsi" STRING NOT NULL,
    "prodiId" STRING NOT NULL,

    CONSTRAINT "CPMK_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "subCPMK" (
    "kode" STRING NOT NULL,
    "deskripsi" STRING NOT NULL,

    CONSTRAINT "subCPMK_pkey" PRIMARY KEY ("kode")
);

-- CreateTable
CREATE TABLE "penilaianCPMK" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kode" STRING NOT NULL,
    "CPLkode" INT4 NOT NULL,
    "MKkode" STRING NOT NULL,
    "CPMKkode" INT4 NOT NULL,
    "tahapPenilaian" STRING NOT NULL,
    "teknikPenilaian" STRING NOT NULL,
    "instrumen" STRING NOT NULL,
    "batasNilai" FLOAT8 NOT NULL,
    "kriteria" JSONB NOT NULL,
    "prodiId" STRING NOT NULL,

    CONSTRAINT "penilaianCPMK_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mahasiswa" (
    "nim" STRING NOT NULL,
    "nama" STRING NOT NULL,
    "prodiId" STRING NOT NULL,

    CONSTRAINT "mahasiswa_pkey" PRIMARY KEY ("nim")
);

-- CreateTable
CREATE TABLE "inputNilai" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "penilaianCPMKId" INT4 NOT NULL,
    "mahasiswaNim" STRING NOT NULL,
    "kelasId" INT4 NOT NULL,
    "nilai" FLOAT8[],
    "prodiId" STRING NOT NULL
);

-- CreateTable
CREATE TABLE "_kelas_dosen" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_cpl_pl" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_cpmk_cpl" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_cpl_bk" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_bk_mk" (
    "A" INT4 NOT NULL,
    "B" STRING NOT NULL
);

-- CreateTable
CREATE TABLE "_kelas_mahasiswa" (
    "A" INT4 NOT NULL,
    "B" STRING NOT NULL
);

-- CreateTable
CREATE TABLE "_cpmk_mk" (
    "A" INT4 NOT NULL,
    "B" STRING NOT NULL
);

-- CreateTable
CREATE TABLE "_cpmk_subcpmk" (
    "A" INT4 NOT NULL,
    "B" STRING NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "prodi_kode_key" ON "prodi"("kode");

-- CreateIndex
CREATE UNIQUE INDEX "account_id_key" ON "account"("id");

-- CreateIndex
CREATE UNIQUE INDEX "account_email_key" ON "account"("email");

-- CreateIndex
CREATE UNIQUE INDEX "PL_id_key" ON "PL"("id");

-- CreateIndex
CREATE UNIQUE INDEX "PL_kode_prodiId_key" ON "PL"("kode", "prodiId");

-- CreateIndex
CREATE UNIQUE INDEX "CPL_id_key" ON "CPL"("id");

-- CreateIndex
CREATE UNIQUE INDEX "CPL_kode_prodiId_key" ON "CPL"("kode", "prodiId");

-- CreateIndex
CREATE UNIQUE INDEX "BK_id_key" ON "BK"("id");

-- CreateIndex
CREATE UNIQUE INDEX "BK_kode_prodiId_key" ON "BK"("kode", "prodiId");

-- CreateIndex
CREATE UNIQUE INDEX "MK_kode_key" ON "MK"("kode");

-- CreateIndex
CREATE UNIQUE INDEX "rencanaPembelajaran_id_key" ON "rencanaPembelajaran"("id");

-- CreateIndex
CREATE UNIQUE INDEX "kelas_id_key" ON "kelas"("id");

-- CreateIndex
CREATE UNIQUE INDEX "CPMK_id_key" ON "CPMK"("id");

-- CreateIndex
CREATE UNIQUE INDEX "CPMK_kode_prodiId_key" ON "CPMK"("kode", "prodiId");

-- CreateIndex
CREATE UNIQUE INDEX "subCPMK_kode_key" ON "subCPMK"("kode");

-- CreateIndex
CREATE UNIQUE INDEX "penilaianCPMK_id_key" ON "penilaianCPMK"("id");

-- CreateIndex
CREATE UNIQUE INDEX "penilaianCPMK_kode_prodiId_key" ON "penilaianCPMK"("kode", "prodiId");

-- CreateIndex
CREATE UNIQUE INDEX "mahasiswa_nim_key" ON "mahasiswa"("nim");

-- CreateIndex
CREATE UNIQUE INDEX "inputNilai_id_key" ON "inputNilai"("id");

-- CreateIndex
CREATE UNIQUE INDEX "_kelas_dosen_AB_unique" ON "_kelas_dosen"("A", "B");

-- CreateIndex
CREATE INDEX "_kelas_dosen_B_index" ON "_kelas_dosen"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_cpl_pl_AB_unique" ON "_cpl_pl"("A", "B");

-- CreateIndex
CREATE INDEX "_cpl_pl_B_index" ON "_cpl_pl"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_cpmk_cpl_AB_unique" ON "_cpmk_cpl"("A", "B");

-- CreateIndex
CREATE INDEX "_cpmk_cpl_B_index" ON "_cpmk_cpl"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_cpl_bk_AB_unique" ON "_cpl_bk"("A", "B");

-- CreateIndex
CREATE INDEX "_cpl_bk_B_index" ON "_cpl_bk"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_bk_mk_AB_unique" ON "_bk_mk"("A", "B");

-- CreateIndex
CREATE INDEX "_bk_mk_B_index" ON "_bk_mk"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_kelas_mahasiswa_AB_unique" ON "_kelas_mahasiswa"("A", "B");

-- CreateIndex
CREATE INDEX "_kelas_mahasiswa_B_index" ON "_kelas_mahasiswa"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_cpmk_mk_AB_unique" ON "_cpmk_mk"("A", "B");

-- CreateIndex
CREATE INDEX "_cpmk_mk_B_index" ON "_cpmk_mk"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_cpmk_subcpmk_AB_unique" ON "_cpmk_subcpmk"("A", "B");

-- CreateIndex
CREATE INDEX "_cpmk_subcpmk_B_index" ON "_cpmk_subcpmk"("B");

-- AddForeignKey
ALTER TABLE "account" ADD CONSTRAINT "account_prodiId_fkey" FOREIGN KEY ("prodiId") REFERENCES "prodi"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PL" ADD CONSTRAINT "PL_prodiId_fkey" FOREIGN KEY ("prodiId") REFERENCES "prodi"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CPL" ADD CONSTRAINT "CPL_prodiId_fkey" FOREIGN KEY ("prodiId") REFERENCES "prodi"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BK" ADD CONSTRAINT "BK_prodiId_fkey" FOREIGN KEY ("prodiId") REFERENCES "prodi"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MK" ADD CONSTRAINT "MK_prodiId_fkey" FOREIGN KEY ("prodiId") REFERENCES "prodi"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rencanaPembelajaran" ADD CONSTRAINT "rencanaPembelajaran_MKId_fkey" FOREIGN KEY ("MKId") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kelas" ADD CONSTRAINT "kelas_MKId_fkey" FOREIGN KEY ("MKId") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CPMK" ADD CONSTRAINT "CPMK_prodiId_fkey" FOREIGN KEY ("prodiId") REFERENCES "prodi"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "penilaianCPMK" ADD CONSTRAINT "penilaianCPMK_CPLkode_fkey" FOREIGN KEY ("CPLkode") REFERENCES "CPL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "penilaianCPMK" ADD CONSTRAINT "penilaianCPMK_MKkode_fkey" FOREIGN KEY ("MKkode") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "penilaianCPMK" ADD CONSTRAINT "penilaianCPMK_CPMKkode_fkey" FOREIGN KEY ("CPMKkode") REFERENCES "CPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "penilaianCPMK" ADD CONSTRAINT "penilaianCPMK_prodiId_fkey" FOREIGN KEY ("prodiId") REFERENCES "prodi"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mahasiswa" ADD CONSTRAINT "mahasiswa_prodiId_fkey" FOREIGN KEY ("prodiId") REFERENCES "prodi"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inputNilai" ADD CONSTRAINT "inputNilai_penilaianCPMKId_fkey" FOREIGN KEY ("penilaianCPMKId") REFERENCES "penilaianCPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inputNilai" ADD CONSTRAINT "inputNilai_mahasiswaNim_fkey" FOREIGN KEY ("mahasiswaNim") REFERENCES "mahasiswa"("nim") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inputNilai" ADD CONSTRAINT "inputNilai_kelasId_fkey" FOREIGN KEY ("kelasId") REFERENCES "kelas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inputNilai" ADD CONSTRAINT "inputNilai_prodiId_fkey" FOREIGN KEY ("prodiId") REFERENCES "prodi"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_kelas_dosen" ADD CONSTRAINT "_kelas_dosen_A_fkey" FOREIGN KEY ("A") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_kelas_dosen" ADD CONSTRAINT "_kelas_dosen_B_fkey" FOREIGN KEY ("B") REFERENCES "kelas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_cpl_pl" ADD CONSTRAINT "_cpl_pl_A_fkey" FOREIGN KEY ("A") REFERENCES "CPL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_cpl_pl" ADD CONSTRAINT "_cpl_pl_B_fkey" FOREIGN KEY ("B") REFERENCES "PL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_cpmk_cpl" ADD CONSTRAINT "_cpmk_cpl_A_fkey" FOREIGN KEY ("A") REFERENCES "CPL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_cpmk_cpl" ADD CONSTRAINT "_cpmk_cpl_B_fkey" FOREIGN KEY ("B") REFERENCES "CPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_cpl_bk" ADD CONSTRAINT "_cpl_bk_A_fkey" FOREIGN KEY ("A") REFERENCES "BK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_cpl_bk" ADD CONSTRAINT "_cpl_bk_B_fkey" FOREIGN KEY ("B") REFERENCES "CPL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_bk_mk" ADD CONSTRAINT "_bk_mk_A_fkey" FOREIGN KEY ("A") REFERENCES "BK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_bk_mk" ADD CONSTRAINT "_bk_mk_B_fkey" FOREIGN KEY ("B") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_kelas_mahasiswa" ADD CONSTRAINT "_kelas_mahasiswa_A_fkey" FOREIGN KEY ("A") REFERENCES "kelas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_kelas_mahasiswa" ADD CONSTRAINT "_kelas_mahasiswa_B_fkey" FOREIGN KEY ("B") REFERENCES "mahasiswa"("nim") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_cpmk_mk" ADD CONSTRAINT "_cpmk_mk_A_fkey" FOREIGN KEY ("A") REFERENCES "CPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_cpmk_mk" ADD CONSTRAINT "_cpmk_mk_B_fkey" FOREIGN KEY ("B") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_cpmk_subcpmk" ADD CONSTRAINT "_cpmk_subcpmk_A_fkey" FOREIGN KEY ("A") REFERENCES "CPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_cpmk_subcpmk" ADD CONSTRAINT "_cpmk_subcpmk_B_fkey" FOREIGN KEY ("B") REFERENCES "subCPMK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;
