/*
  Warnings:

  - You are about to drop the `_mk_mahasiswa` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "_mk_mahasiswa" DROP CONSTRAINT "_mk_mahasiswa_A_fkey";

-- DropForeignKey
ALTER TABLE "_mk_mahasiswa" DROP CONSTRAINT "_mk_mahasiswa_B_fkey";

-- DropTable
DROP TABLE "_mk_mahasiswa";

-- CreateTable
CREATE TABLE "kelas" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nama" STRING NOT NULL,
    "MKId" STRING NOT NULL,
    "jumlahLulus" INT4 NOT NULL,
    "mahasiswaLulus" JSONB,

    CONSTRAINT "kelas_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_kelas_mahasiswa" (
    "A" INT4 NOT NULL,
    "B" STRING NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "kelas_id_key" ON "kelas"("id");

-- CreateIndex
CREATE UNIQUE INDEX "_kelas_mahasiswa_AB_unique" ON "_kelas_mahasiswa"("A", "B");

-- CreateIndex
CREATE INDEX "_kelas_mahasiswa_B_index" ON "_kelas_mahasiswa"("B");

-- AddForeignKey
ALTER TABLE "kelas" ADD CONSTRAINT "kelas_MKId_fkey" FOREIGN KEY ("MKId") REFERENCES "MK"("kode") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_kelas_mahasiswa" ADD CONSTRAINT "_kelas_mahasiswa_A_fkey" FOREIGN KEY ("A") REFERENCES "kelas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_kelas_mahasiswa" ADD CONSTRAINT "_kelas_mahasiswa_B_fkey" FOREIGN KEY ("B") REFERENCES "mahasiswa"("nim") ON DELETE CASCADE ON UPDATE CASCADE;
