/*
  Warnings:

  - You are about to drop the column `jumlahLulus` on the `MK` table. All the data in the column will be lost.

*/
-- AlterSequence
ALTER SEQUENCE "CPL_id_seq" MAXVALUE 9223372036854775807;

-- AlterTable
ALTER TABLE "MK" DROP COLUMN "jumlahLulus";

-- CreateTable
CREATE TABLE "lulusMK_CPMK" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "MKId" STRING NOT NULL,
    "tahunAjaranId" INT4 NOT NULL,
    "CPMKId" INT4 NOT NULL,
    "jumlahLulus" INT4 NOT NULL,

    CONSTRAINT "lulusMK_CPMK_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lulusMK" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "MKId" STRING NOT NULL,
    "tahunAjaranId" INT4 NOT NULL,
    "jumlahLulus" INT4 NOT NULL,

    CONSTRAINT "lulusMK_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lulusKelas_CPMK" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kelasId" INT4 NOT NULL,
    "CPMKId" INT4 NOT NULL,
    "tahunAjaranId" INT4 NOT NULL,
    "jumlahLulus" INT4 NOT NULL,

    CONSTRAINT "lulusKelas_CPMK_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lulusCPMK" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CPMKId" INT4 NOT NULL,
    "tahunAjaranId" INT4 NOT NULL,
    "jumlahLulus" INT4 NOT NULL,

    CONSTRAINT "lulusCPMK_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "lulusMK_CPMK_id_key" ON "lulusMK_CPMK"("id");

-- CreateIndex
CREATE UNIQUE INDEX "lulusMK_id_key" ON "lulusMK"("id");

-- CreateIndex
CREATE UNIQUE INDEX "lulusKelas_CPMK_id_key" ON "lulusKelas_CPMK"("id");

-- CreateIndex
CREATE UNIQUE INDEX "lulusCPMK_id_key" ON "lulusCPMK"("id");

-- AddForeignKey
ALTER TABLE "lulusMK_CPMK" ADD CONSTRAINT "lulusMK_CPMK_MKId_fkey" FOREIGN KEY ("MKId") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lulusMK_CPMK" ADD CONSTRAINT "lulusMK_CPMK_tahunAjaranId_fkey" FOREIGN KEY ("tahunAjaranId") REFERENCES "tahunAjaran"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lulusMK_CPMK" ADD CONSTRAINT "lulusMK_CPMK_CPMKId_fkey" FOREIGN KEY ("CPMKId") REFERENCES "CPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lulusMK" ADD CONSTRAINT "lulusMK_MKId_fkey" FOREIGN KEY ("MKId") REFERENCES "MK"("kode") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lulusMK" ADD CONSTRAINT "lulusMK_tahunAjaranId_fkey" FOREIGN KEY ("tahunAjaranId") REFERENCES "tahunAjaran"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lulusKelas_CPMK" ADD CONSTRAINT "lulusKelas_CPMK_kelasId_fkey" FOREIGN KEY ("kelasId") REFERENCES "kelas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lulusKelas_CPMK" ADD CONSTRAINT "lulusKelas_CPMK_CPMKId_fkey" FOREIGN KEY ("CPMKId") REFERENCES "CPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lulusKelas_CPMK" ADD CONSTRAINT "lulusKelas_CPMK_tahunAjaranId_fkey" FOREIGN KEY ("tahunAjaranId") REFERENCES "tahunAjaran"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lulusCPMK" ADD CONSTRAINT "lulusCPMK_CPMKId_fkey" FOREIGN KEY ("CPMKId") REFERENCES "CPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lulusCPMK" ADD CONSTRAINT "lulusCPMK_tahunAjaranId_fkey" FOREIGN KEY ("tahunAjaranId") REFERENCES "tahunAjaran"("id") ON DELETE CASCADE ON UPDATE CASCADE;
