/*
  Warnings:

  - A unique constraint covering the columns `[id]` on the table `penilaianCPMK` will be added. If there are existing duplicate values, this will fail.
  - A unique constraint covering the columns `[kode,prodiId]` on the table `penilaianCPMK` will be added. If there are existing duplicate values, this will fail.
  - Changed the type of `penilaianCPMKId` on the `inputNilai` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- DropForeignKey
ALTER TABLE "inputNilai" DROP CONSTRAINT "inputNilai_penilaianCPMKId_fkey";

-- DropIndex
DROP INDEX "penilaianCPMK_kode_key";

-- AlterTable
ALTER TABLE "inputNilai" DROP COLUMN "penilaianCPMKId";
ALTER TABLE "inputNilai" ADD COLUMN     "penilaianCPMKId" INT4 NOT NULL;

-- AlterTable
ALTER TABLE "penilaianCPMK" ADD COLUMN     "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY;

-- AlterPrimaryKey
ALTER TABLE "penilaianCPMK" ALTER PRIMARY KEY USING COLUMNS ("id");

-- CreateIndex
CREATE UNIQUE INDEX "penilaianCPMK_id_key" ON "penilaianCPMK"("id");

-- CreateIndex
CREATE UNIQUE INDEX "penilaianCPMK_kode_prodiId_key" ON "penilaianCPMK"("kode", "prodiId");

-- AddForeignKey
ALTER TABLE "inputNilai" ADD CONSTRAINT "inputNilai_penilaianCPMKId_fkey" FOREIGN KEY ("penilaianCPMKId") REFERENCES "penilaianCPMK"("id") ON DELETE CASCADE ON UPDATE CASCADE;
